import React from 'react';

const allData = [
  {
    id: 1,
    img: "https://allsmiledentalclinics.com/wp-content/uploads/2022/01/DANSOMAN.jpg",
    name: "All Smile Dental Clinic",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
  },
  {
    id: 2,
    img: "https://i0.wp.com/sonrisagh.com/wp-content/uploads/2022/11/sonrisa-home1.jpg?fit=537%2C549&ssl=1",
    name: "Sonrisa Clinic",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
  },
  {
    id: 3,
    img: "https://qph.cf2.quoracdn.net/main-qimg-6cc29eec1bf8c00c698c08fd007b26e2-lq",
    name: "Airport Women Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    services: ""
  },
  {
    id: 4,
    img: "https://perkinswill.com/wp-content/uploads/2019/05/RidgeHospital_F1A3258_20170102-low-res.jpg",
    name: "Ridge Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Ear, Nose & Throat",
  },
  {
    id: 5,
    img: "https://britanniamedical.org/assets/Britannia.jpg",
    name: "Britannia Medical Centre",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
  },
  {
    id: 6,
    img: "https://qph.cf2.quoracdn.net/main-qimg-6cc29eec1bf8c00c698c08fd007b26e2-lq",
    name: "Airport Women Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Dental"
  },
  {
    id: 7,
    img: "https://perkinswill.com/wp-content/uploads/2019/05/RidgeHospital_F1A3258_20170102-low-res.jpg",
    name: "Ridge Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Tema Comm 25, Prampram road",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Laboratory",
  },
  {
    id: 8,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMawuDtgnI9CBIrOi9omMcMJwNqz6O34rJ7Qlx_323fw&s",
    name: "UG Medical Hospital",
    price: "GHC 500 - GHC 1500",
    location: "UG Campus",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Laboratory",
  },
  {
    id: 9,
    img: "https://britanniamedical.org/assets/Britannia.jpg",
    name: "Britannia Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Tema",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Laboratory",
  },
  {
    id: 10,
    img: "https://lh3.googleusercontent.com/p/AF1QipPmAENn3JKVb9MHQWcYTvdJWj4hP3AkPvkyN5w=s680-w680-h510",
    name: "St. Michael's Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Adabraka",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Surgical",
  },
  {
    id: 11,
    img: "https://www.myjoyonline.com/wp-content/uploads/2023/02/Siaw-Agyepong-Ward1.jpeg",
    name: "37 Military Hospital",
    price: "GHC 500 - GHC 1500",
    location: "UG Campus",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Category 1",
  },
  {
    id: 12,
    img: "https://lh3.googleusercontent.com/p/AF1QipPmAENn3JKVb9MHQWcYTvdJWj4hP3AkPvkyN5w=s680-w680-h510",
    name: "UG Medical Hospital",
    price: "GHC 500 - GHC 1500",
    location: "UG Campus",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
  },
];

export default allData;
