import React from 'react';

const topratedData = [
  {
    id: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMawuDtgnI9CBIrOi9omMcMJwNqz6O34rJ7Qlx_323fw&s",
    name: "UG Medical Hospital",
    price: "GHC 500 - GHC 1500",
    location: "UG Campus",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Laboratory",
  },
  {
    id: 2,
    img: "https://britanniamedical.org/assets/Britannia.jpg",
    name: "Britannia Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Tema",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Laboratory",
  },
  {
    id: 3,
    img: "https://lh3.googleusercontent.com/p/AF1QipPmAENn3JKVb9MHQWcYTvdJWj4hP3AkPvkyN5w=s680-w680-h510",
    name: "St. Michael's Hospital",
    price: "GHC 500 - GHC 1500",
    location: "Adabraka",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Surgical",
  },
  {
    id: 4,
    img: "https://www.myjoyonline.com/wp-content/uploads/2023/02/Siaw-Agyepong-Ward1.jpeg",
    name: "37 Military Hospital",
    price: "GHC 500 - GHC 1500",
    location: "UG Campus",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
    category: "Category 1",
  },
  {
    id: 5,
    img: "https://lh3.googleusercontent.com/p/AF1QipPmAENn3JKVb9MHQWcYTvdJWj4hP3AkPvkyN5w=s680-w680-h510",
    name: "UG Medical Hospital",
    price: "GHC 500 - GHC 1500",
    location: "UG Campus",
    hours: "Mon - Sat (9:00am - 11:00pm)",
    contact: "0307514781 / 0300478541",
    review1: "I enjoyed the service delivery. It is a clean and serene environment",
    review2: "The staff were experienced and professional",
    review3: "I will definitely go there anytime I need medical service",
  },
  
];

export default topratedData;
